apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gd23jh9up-java-springboot 
  janus-idp.io/tekton: gd23jh9up-java-springboot
  backstage.io/kubernetes-id: gd23jh9up-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gd23jh9up-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  